### ISSUE TITLE
deploy to npm

### ISSUE THREAD

**Issue by jbcpollak** [behavior3/behavior3js#10]
Seems like the project is not deployed to npm... that would make it easier to adopt in other projects

**Comment by jwallden** [comment]
I just installed this via npm!

**Comment by scowling** [comment]
@jwallden care to share how?

**Comment by jwallden** [comment]
Sure!
`npm install behavior3js`

**Comment by scowling** [comment]
Ha! of course.. on this side of the world we spell behavior -> behaviour

which obviously doesn't help an npm install search!

**Comment by jwallden** [comment]
At least you're a native english speaker. Imagine how the rest of us struggle! ;) 

Glad you found it! I suggest closing the issue.

**Comment by renatopp** [comment]
I'm closing this issue, you may reopen it if needed.
