### ISSUE TITLE
Simple implementation example [$20 awarded]

### ISSUE THREAD

**Issue by Sladix** [behavior3/behavior3js#2]
Could you please write a simple implementation example ? For example an agent behavior that roam randomly and eat when it's hungry ?

I'm very interested in learning and implementing tree behavior in js but must say I don't clearly see how to implement it in a basic architecture.

Thanks :)
##

**Comment by renatopp** [comment]
We already talked via email, I'm going to keep this thread open to remind the need for proper examples.

**Comment by ruyadorno** [comment]
something similar to the example from `statejs` would be awesome :smile:

**Comment by tjpalmer** [comment]
Is this to say that nobody has actually ever used Behavior3?

**Comment by EskelCz** [comment]
I'd love this as well. Raising the bounty :)

**Comment by elicwhite** [comment]
I used this library in an AI for the game [screeps](https://screeps.com/). Repo and main file here: https://github.com/TheSavior/screeps/blob/master/src/main.js

I had to write my own blackboard to work with the screeps memory system. I also had to change the way IDs were calculated since every frame has an entirely new context. If you are writing a typical program, you probably wouldn't need to do that hackery.

**Comment by soundyogi** [comment]
It is used here aswell:

http://guineashots.com/democracy/

**Comment by efbenson** [comment]
I messed around with the current implementation and got it working in node and built a quick example using the code in democracy as a guide.  It is built on nodejs, but should work in the browser as well.

https://github.com/efbenson/behavior3Test

**Comment by EskelCz** [comment]
@efbenson I think this is perfect, thank you!
I think you should claim the bounty. Hopefully @Sladix will close the thread and award it. (Not sure how it works really.)

**Comment by Sladix** [comment]
Dunno how to award the bounty :/

**Comment by renatopp** [comment]
Nice!

For the bounty, I think you ( @efbenson ) have to go in 

https://www.bountysource.com/issues/25025597-simple-implementation-example

and claim de bounty. I don't see any option for me to give you directly.

**Comment by efbenson** [comment]
Done. Thanks guys.

**Comment by gocpplua** [comment]
> I messed around with the current implementation and got it working in node and built a quick example using the code in democracy as a guide. It is built on nodejs, but should work in the browser as well.
> 
> https://github.com/efbenson/behavior3Test

This example is very good
