### ISSUE TITLE
Modernize the codebase

### ISSUE THREAD

**Issue by jgamedev** [behavior3/behavior3js#21]
JavaScript has moved on and so should this awesome codebase.

I plan to use this fork ( https://github.com/yagl/behavior3 )  for my project  because it uses ES2015 and a Babel workflow, it's a pity I can't use the original version of the library :wink:  
##

**Comment by renatopp** [comment]
Hey @jgamedev, thanks for the feedback. I'm doing exactly that, but starting with the editor. C:

**Comment by chrisl8** [comment]
Any update on this?

**Comment by danielepolencic** [comment]
This library supports Node.js & Babel now 🎉 

PRs to improve the codebase are always welcome.
