### ISSUE TITLE
Use ES6 classes

### ISSUE THREAD

**Issue by Oza94** [behavior3/behavior3js#3]
Hello,

Javascript classes have been released in June 2015 under the EcmaScript 6 specification. It would be great if behavior3js use them instead of its own class utility.

To ensure compatibility with browsers, we'll need to use something like babel to transpile ES6 to ES5.

This change will be heavy, but since there is a test suit we can do it without breaking features.
##

**Comment by renatopp** [comment]
I'm not very familiar with ES6, but I would like to port b3 to it. How it is to translate es6 to es5? How we would use a Class system in the es5 if translated?

**Comment by Oza94** [comment]
I'm currently following [your tutorial](http://guineashots.com/2014/09/24/implementing-a-behavior-tree-part-1/) for my own implementation in ES6. I will push my work on [this repository](https://github.com/quest-engine/behavior3).

I would like to use your lib in the future for the benefits of the editor (and merged efforts :) ), my implementation is a temporary work in the meantime because I need it now.

For documentation on ES6 and classes you can start with [this page](https://github.com/lukehoban/es6features#classes). To transpile ES6 to compatible ES5, you can use Babel, there is a [live editor](https://babeljs.io/repl/) where you can try the new syntax and see live how it compile.

On my wip implementation, here is how the `Sequence` node implementation looks like:

``` es6

import State from './../constants/state';
import BaseNode from './../basenode';

export default class Sequence extends BaseNode {
  constructor(childs) {
    super();

    this.name = 'Sequence';
    this.childs = [];
    childs.map(c => this.childs.push(c));
  }
  tick(tick) {
    for (var i = 0; i < this.childs.length; i += 1) {
      var status = this.childs[i].execute();

      if (status !== State.SUCCESS) {
        return status;
      }
    }

    return State.SUCCESS;
  }
}
```

**Comment by ruyadorno** [comment]
I'd also like to recommend the work of Dr. Axel on both his [blog](http://www.2ality.com/2015/08/getting-started-es6.html) and [book](http://exploringjs.com/)

**Comment by mickdekkers** [comment]
This issue seems to be covered by #21 (Modernize the codebase). @renatopp is it worth considering closing this issue and directing further discussion to #21?

**Comment by danielepolencic** [comment]
@Oza94 would like to submit a PR to convert all classes to ES6?

**Comment by Zielak** [comment]
Hi, @danielepolencic !
I couldn't wait so I gave it a try: #30

**Comment by danielepolencic** [comment]
@Zielak made the dream come true ✨ 

https://github.com/behavior3/behavior3js/pull/30

Closing this.
