### ISSUE TITLE
behavior3.com domain expired

### ISSUE THREAD

**Issue by Behery** [behavior3/behavior3js#35]
The site for the editor/demo isn't working anymore

**Comment by ldd** [comment]
Yes, if anybody else finds themselves here, you can still run a (local) version of the editor.

Steps:
1. Git clone [behavior3editor](https://github.com/behavior3/behavior3editor)
2. Run `npm install` and `bower install` (you may need to install bower globally)
3. Run `gulp serve` (you may need to install gulp globally)
