### ISSUE TITLE
Usage in node.js produces error unless I define b3 in the global namespace first

### ISSUE THREAD

**Issue by chrisl8** [behavior3/behavior3js#4]
I am using behaviro3js in node.js, and it works, except that I have to declare an empty b3 object in the global scope first.

This works:

```
b3 = {}
var behavior3js = require('behavior3js');
```

However, if I just do this:

```
var behavior3js = require('behavior3js');
```

without the "b3" declaration I receive this error:

```
_filename, __dirname) { this.b3=this.b3||{},function(){"use strict";b3.VERSION
                                                                    ^
ReferenceError: b3 is not defined
```
##

**Comment by renatopp** [comment]
There are some pending updates on b3js, I hope to fix that together.

**Comment by elicwhite** [comment]
+1

**Comment by chrisl8** [comment]
This is fixed with the new updates introduced by @danielepolencic
