### ISSUE TITLE
npm pulls from wrong repository

### ISSUE THREAD

**Issue by chrisl8** [behavior3/behavior3js#5]
`npm install behavior3js` is pulling version 0.1.0 from https://github.com/renatopp/behavior3js instead of the current version from https://github.com/behavior3/behavior3js

EDIT: I just tried the new version and it breaks in node.js, so maybe it is best that npm points to the old version until use of behavior3js in node.js is sorted out fully.

**Comment by renatopp** [comment]
Hey @chrisl8 , thanks for the feedback. The version in repository is not released yet (it is depending on some updates of the editor). So version 0.1.0 is the thing right now.

I hope to fix these node.js problems with these new updates.

Closing this for now, feel free to reopen it if necessary.
