### ISSUE TITLE
Build tasks combines classes in wrong order, breaking inheritanc

### ISSUE THREAD

**Issue by marrone** [behavior3/behavior3js#8]
The gulp build task does not explicitly specify the order of inclusion of the main classes (BaseNode, etc), when concatenating. The result may have the child classes defined first before the parent classes which results in them inheriting from "null" when calls b3.Class(...)

**Comment by soundyogi** [comment]
Merging this would be rrrreally great :)

**Comment by renatopp** [comment]
Partial merging on 355f925
